version: '3.5'

services:
 jupyter:
    image: jupyter/pyspark-notebook:spark-3.1.2  
    build:
      context: .
      dockerfile: Dockerfile-jupyter
    environment:
      JUPYTER_TOKEN: "de292180cef310dff64df49c25228b87e600c506f2b9cdfc"
    ports:
      - "8888:8888"
    volumes:
      - /home/jovyan
      #A file needs to be mounted against a file, not a directory
      - ./DatabaseConnections.ipynb:/home/jovyan/work/DatabaseConnections.ipynb
    restart: unless-stopped
    depends_on:
     - postgres
     - spark