version: '3.5'

services:
 jupyter:
    image: jupyter/datascience-notebook  
    build:
      context: .
      dockerfile: Dockerfile-jupyter
    environment:
      JUPYTER_TOKEN: "3764abdc2d9b4604f4d52cc5f433ecb2ed882589215ab91e"
    ports:
      - "8888:8888"
    volumes:
      - /home/jovyan
      #A file needs to be mounted against a file, not a directory
      - ./DatabaseConnections.ipynb:/home/jovyan/work/DatabaseConnections.ipynb
    restart: unless-stopped
    depends_on:
     - postgres
     - redis